begin;

create extension if not exists "pgcrypto" with schema extensions;

create table if not exists public.wallet_accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique,
  device_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint wallet_accounts_identity_check check (user_id is not null or (device_id is not null and length(trim(device_id)) > 0))
);

create table if not exists public.wallet_ledger (
  id bigint generated by default as identity primary key,
  account_id uuid not null references public.wallet_accounts(id) on delete cascade,
  delta integer not null check (delta <> 0),
  reason text not null,
  source text not null default 'system',
  idempotency_key text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_wallet_ledger_account_created_at on public.wallet_ledger (account_id, created_at desc);
create unique index if not exists wallet_ledger_idempotency_unique on public.wallet_ledger (account_id, idempotency_key) where idempotency_key is not null;

alter table public.wallet_accounts enable row level security;
alter table public.wallet_ledger enable row level security;

drop policy if exists "Users can view own wallet accounts" on public.wallet_accounts;
drop policy if exists "Users can view own wallet ledger" on public.wallet_ledger;

create policy "Users can view own wallet accounts" on public.wallet_accounts
  for select
  to authenticated
  using (user_id = auth.uid());

create policy "Users can view own wallet ledger" on public.wallet_ledger
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.wallet_accounts a
      where a.id = wallet_ledger.account_id
        and a.user_id = auth.uid()
    )
  );

create or replace function public.wallet_resolve_account(p_user_id uuid, p_device_id text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_device_id text := nullif(trim(p_device_id), '');
  v_account_id uuid;
  v_device_account_id uuid;
begin
  if p_user_id is null and v_device_id is null then
    raise exception 'MISSING_IDENTITY';
  end if;

  if p_user_id is not null then
    select id into v_account_id
    from public.wallet_accounts
    where user_id = p_user_id
    limit 1;

    if v_account_id is null and v_device_id is not null then
      select id into v_account_id
      from public.wallet_accounts
      where device_id = v_device_id
      limit 1;

      if v_account_id is not null then
        update public.wallet_accounts
        set user_id = p_user_id, updated_at = now()
        where id = v_account_id;
      end if;
    end if;

    if v_account_id is null then
      insert into public.wallet_accounts (user_id, device_id)
      values (p_user_id, v_device_id)
      returning id into v_account_id;
    end if;

    if v_device_id is not null then
      select id into v_device_account_id
      from public.wallet_accounts
      where device_id = v_device_id
        and id <> v_account_id
      limit 1;

      if v_device_account_id is not null then
        update public.wallet_ledger
        set account_id = v_account_id
        where account_id = v_device_account_id;

        delete from public.wallet_accounts
        where id = v_device_account_id;
      end if;

      update public.wallet_accounts
      set device_id = v_device_id, updated_at = now()
      where id = v_account_id;
    end if;

    return v_account_id;
  end if;

  select id into v_account_id
  from public.wallet_accounts
  where device_id = v_device_id
  limit 1;

  if v_account_id is null then
    insert into public.wallet_accounts (device_id)
    values (v_device_id)
    returning id into v_account_id;
  end if;

  return v_account_id;
end;
$$;

create or replace function public.wallet_get_balance(p_user_id uuid, p_device_id text)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_account_id uuid;
  v_balance integer;
begin
  v_account_id := public.wallet_resolve_account(p_user_id, p_device_id);

  select coalesce(sum(delta), 0)::integer
  into v_balance
  from public.wallet_ledger
  where account_id = v_account_id;

  return v_balance;
end;
$$;

create or replace function public.wallet_apply_delta(
  p_user_id uuid,
  p_device_id text,
  p_delta integer,
  p_reason text,
  p_source text default 'system',
  p_idempotency_key text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_account_id uuid;
  v_balance integer;
begin
  if p_delta = 0 then
    raise exception 'INVALID_DELTA';
  end if;

  v_account_id := public.wallet_resolve_account(p_user_id, p_device_id);

  perform 1 from public.wallet_accounts where id = v_account_id for update;

  select coalesce(sum(delta), 0)::integer
  into v_balance
  from public.wallet_ledger
  where account_id = v_account_id;

  if p_delta < 0 and v_balance + p_delta < 0 then
    raise exception 'INSUFFICIENT_COINS';
  end if;

  if p_idempotency_key is null then
    insert into public.wallet_ledger (account_id, delta, reason, source, metadata)
    values (v_account_id, p_delta, p_reason, p_source, coalesce(p_metadata, '{}'::jsonb));
    v_balance := v_balance + p_delta;
    return v_balance;
  end if;

  insert into public.wallet_ledger (account_id, delta, reason, source, idempotency_key, metadata)
  values (v_account_id, p_delta, p_reason, p_source, p_idempotency_key, coalesce(p_metadata, '{}'::jsonb))
  on conflict (account_id, idempotency_key) where idempotency_key is not null do nothing;

  select coalesce(sum(delta), 0)::integer
  into v_balance
  from public.wallet_ledger
  where account_id = v_account_id;

  return v_balance;
end;
$$;

grant execute on function public.wallet_get_balance(uuid, text) to anon, authenticated, service_role;
grant execute on function public.wallet_apply_delta(uuid, text, integer, text, text, text, jsonb) to authenticated, service_role;
grant execute on function public.wallet_resolve_account(uuid, text) to authenticated, service_role;

commit;
